#!/usr/bin/env python3
# generate_changelog.py
# Tự động tạo CHANGELOG.md từ lịch sử commit Git

import argparse
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
from git import Repo, TagReference, Commit

# Định nghĩa các danh mục thay đổi dựa trên tiền tố commit
CHANGE_CATEGORIES = {
    "feat": "Added",
    "fix": "Fixed",
    "docs": "Documentation",
    "style": "Style",
    "refactor": "Refactored",
    "perf": "Performance",
    "test": "Tests",
    "build": "Build",
    "ci": "CI",
    "chore": "Chores",
    "revert": "Reverted",
    "remove": "Removed",
}

# Đường dẫn đến file CHANGELOG.md
ROOT = Path(__file__).resolve().parent
OUT = ROOT / "CHANGELOG.md"

def parse_commit_message(message: str) -> tuple[Optional[str], str]:
    """Phân tích thông điệp commit để lấy danh mục và mô tả."""
    match = re.match(r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|remove)(\(.+\))?: (.+)$", message, re.IGNORECASE)
    if match:
        category, _, description = match.groups()
        return category.lower(), description.strip()
    return None, message.strip()

def get_version_from_tag(tag: Optional[TagReference], commit: Commit) -> str:
    """Lấy phiên bản từ tag Git hoặc tạo phiên bản mặc định."""
    if tag:
        return tag.name
    # Nếu không có tag, sử dụng ngày commit làm phiên bản tạm
    commit_date = commit.committed_datetime.strftime("%Y%m%d")
    return f"Unreleased-{commit_date}"

def collect_changes(repo: Repo) -> Dict[str, Dict[str, List[str]]]:
    """Thu thập các thay đổi từ lịch sử commit và nhóm theo phiên bản."""
    changes: Dict[str, Dict[str, List[str]]] = {}
    current_tag: Optional[TagReference] = None
    tags = sorted(repo.tags, key=lambda t: t.commit.committed_datetime, reverse=True)

    for commit in repo.iter_commits():
        # Tìm tag liên quan đến commit hiện tại
        commit_tags = [t for t in tags if t.commit == commit]
        if commit_tags:
            current_tag = commit_tags[0]
        
        version = get_version_from_tag(current_tag, commit)
        if version not in changes:
            changes[version] = {cat: [] for cat in CHANGE_CATEGORIES.values()}
            changes[version]["date"] = commit.committed_datetime.strftime("%Y-%m-%d")
        
        # Phân tích thông điệp commit
        category, description = parse_commit_message(commit.message)
        if category and category in CHANGE_CATEGORIES:
            changes[version][CHANGE_CATEGORIES[category]].append(description)
        else:
            changes[version]["Chores"].append(description)
    
    return changes

def generate_changelog(append: bool = False):
    """Tạo nội dung CHANGELOG.md từ các thay đổi."""
    try:
        repo = Repo(ROOT)
    except Exception as e:
        print(f"❌ Lỗi: Không tìm thấy Git repository tại {ROOT}. {str(e)}")
        return

    changes = collect_changes(repo)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Tạo nội dung changelog
    changelog_lines = [
        "# Changelog",
        "All notable changes to this project will be documented in this file.",
        "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).",
        f"\n**Generated:** {now}\n",
    ]

    # Nếu append, đọc nội dung hiện có và chỉ thêm các thay đổi mới
    existing_content = ""
    if append and OUT.exists():
        existing_content = OUT.read_text(encoding="utf-8")
        changelog_lines = [existing_content]

    # Thêm các thay đổi theo phiên bản
    for version, categories in changes.items():
        changelog_lines.append(f"\n## [{version}] - {categories['date']}")
        for category, descriptions in categories.items():
            if category == "date" or not descriptions:
                continue
            changelog_lines.append(f"\n### {category}")
            for desc in sorted(set(descriptions)):  # Loại bỏ trùng lặp và sắp xếp
                changelog_lines.append(f"- {desc}")

    changelog_lines.append("\n---\n\n> This file is automatically generated by `generate_changelog.py`. Do not edit manually!")

    # Ghi file
    OUT.write_text("\n".join(changelog_lines), encoding="utf-8")
    print(f"✅ CHANGELOG.md created/updated at {OUT}")
    print(f" - Versions processed: {len(changes)}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate CHANGELOG.md from Git commits")
    parser.add_argument("--append", action="store_true", help="Nối vào file CHANGELOG.md hiện có thay vì ghi đè")
    args = parser.parse_args()

    generate_changelog(append=args.append)