# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lane.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/lane.proto\x12\x04lane\"\x1c\n\x0bLaneRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"Q\n\x08LaneData\x12\x0b\n\x03\x62ox\x18\x01 \x03(\x02\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\x05\x12\x12\n\nclass_name\x18\x04 \x01(\t\"#\n\x08LaneMeta\x12\x17\n\x0fprocessing_time\x18\x01 \x01(\x01\"\x8c\x01\n\rLaneDeparture\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0blane_offset\x18\x03 \x01(\x02\x12!\n\tleft_lane\x18\x04 \x01(\x0b\x32\x0e.lane.LaneData\x12\"\n\nright_lane\x18\x05 \x01(\x0b\x32\x0e.lane.LaneData\"}\n\x0cLaneResponse\x12\"\n\ndetections\x18\x01 \x03(\x0b\x32\x0e.lane.LaneData\x12\x1c\n\x04meta\x18\x02 \x01(\x0b\x32\x0e.lane.LaneMeta\x12+\n\x0elane_departure\x18\x03 \x01(\x0b\x32\x13.lane.LaneDeparture2?\n\x0bLaneService\x12\x30\n\x07Predict\x12\x11.lane.LaneRequest\x1a\x12.lane.LaneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.lane_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LANEREQUEST']._serialized_start=26
  _globals['_LANEREQUEST']._serialized_end=54
  _globals['_LANEDATA']._serialized_start=56
  _globals['_LANEDATA']._serialized_end=137
  _globals['_LANEMETA']._serialized_start=139
  _globals['_LANEMETA']._serialized_end=174
  _globals['_LANEDEPARTURE']._serialized_start=177
  _globals['_LANEDEPARTURE']._serialized_end=317
  _globals['_LANERESPONSE']._serialized_start=319
  _globals['_LANERESPONSE']._serialized_end=444
  _globals['_LANESERVICE']._serialized_start=446
  _globals['_LANESERVICE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
